** 1.Using Logistic regression**

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [76]:
df = pd.read_csv('mobile_price_range_data.csv')

In [77]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [78]:
df.shape

(2000, 21)

In [79]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [80]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [81]:
x=df.drop('price_range',axis=1)
y=df['price_range']

print(type(x))
print(type(y))

print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


In [82]:
print(x.shape)
print(y.shape)
print(0.25*2000)

(2000, 20)
(2000,)
500.0


**Split the data into training and testing data**

In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


In [84]:
from sklearn.preprocessing import StandardScaler
sclr = StandardScaler()
x_train = pd.DataFrame(sclr.fit_transform(x_train),columns=x_train.columns)
x_test = pd.DataFrame(sclr.fit_transform(x_test),columns=x_test.columns)

**creating Functions to compute matrix_classification_report**

In [85]:
from sklearn.metrics import confusion_matrix,classification_report

In [86]:
def eval_model(ytest,ypred):
  cm = confusion_matrix(ytest,ypred)
  print(cm)
  print(classification_report(ytest,ypred))


**Build the model**

In [87]:
from sklearn.linear_model import LogisticRegression


**Training the ML Model**

In [88]:
m1=LogisticRegression()
m1.fit(x_train,y_train)

# Model is trained on the trained data and Prediction is applied on the test data 

LogisticRegression()

**Evaluate the training and testing score 


In [89]:
## In classification we dont have the r2 score
## We have the Accuracy


print('Training score',m1.score(x_train,y_train))
print('Testing score',m1.score(x_test,y_test))

Training score 0.978
Testing score 0.944


**Generate the Prediction**

In [90]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[0 1 3 2 0 2 0 2 1 0 1 1 2 0 1 2 1 3 1 0 1 3 2 1 1 2 1 1 0 0 3 1 1 0 1 1 1
 2 0 2 2 1 0 3 0 3 0 3 3 1 0 3 0 3 3 2 0 0 3 3 3 0 0 0 0 0 3 0 1 3 1 3 0 0
 2 1 2 2 0 1 1 1 3 1 2 2 3 3 1 0 3 3 2 3 1 1 2 3 3 1 0 2 0 1 2 2 2 3 1 1 2
 0 2 0 0 2 0 3 3 0 3 3 0 2 3 0 2 1 0 3 3 3 3 2 1 2 0 1 3 3 3 2 1 3 0 3 0 3
 0 0 1 2 2 2 2 3 2 2 1 1 1 2 0 0 3 1 0 0 2 3 2 1 0 1 0 3 0 3 0 0 1 1 1 0 2
 3 3 1 1 3 3 3 1 2 3 3 0 3 1 1 3 0 3 2 1 3 3 0 2 0 2 0 0 1 0 3 0 1 1 3 1 0
 3 1 3 1 3 3 3 3 0 2 2 2 1 1 0 1 0 3 2 0 3 2 1 0 3 1 1 0 1 3 2 2 2 3 0 0 2
 0 1 2 2 2 2 0 1 1 2 0 1 2 2 1 2 2 1 1 3 1 3 1 0 0 3 2 1 2 2 3 1 3 1 0 3 0
 1 3 3 0 0 1 1 1 0 3 3 3 3 3 1 1 0 1 2 0 0 2 3 1 0 2 0 0 1 1 2 3 1 1 2 3 1
 3 0 2 3 1 0 3 1 3 1 2 2 2 1 3 3 3 3 1 0 3 1 1 3 0 1 2 1 2 1 0 2 0 0 3 2 3
 2 3 2 1 0 1 1 3 1 1 1 2 1 2 3 0 0 2 0 2 1 3 3 2 2 1 3 1 3 3 2 3 1 1 3 0 2
 1 1 3 0 2 2 1 1 1 2 0 0 0 1 0 0 3 3 1 0 1 3 3 3 3 1 1 2 2 3 1 0 3 2 2 0 0
 2 0 0 1 1 0 0 0 1 0 2 2 2 1 1 0 0 3 3 1 2 2 0 0 0 2 1 2 2 3 0 1 2 1 2 1 0
 3 3 0 2 3 1 2 2 1 3 1 1 

**Evaluate confusion matrix,classification report**

In [91]:
eval_model(y_test, ypred_m1)

[[117   2   0   0]
 [  6 124   0   0]
 [  0  13 109   6]
 [  0   0   1 122]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       119
           1       0.89      0.95      0.92       130
           2       0.99      0.85      0.92       128
           3       0.95      0.99      0.97       123

    accuracy                           0.94       500
   macro avg       0.95      0.95      0.94       500
weighted avg       0.95      0.94      0.94       500



In [92]:
m=m1.coef_
c=m1.intercept_
print(m)
print(c)

# p= 1/(1+e^-(mx+c)

[[-2.58191959e+00 -5.78939358e-02  3.61236417e-02  1.33989555e-01
  -9.96625845e-02 -1.65121608e-02 -1.84946794e-01 -6.17795612e-02
   4.58844144e-01  3.74509736e-02  1.29422872e-03 -1.46313583e+00
  -1.53987852e+00 -1.05606732e+01 -6.78144141e-02 -5.39816847e-03
  -5.27446583e-02 -6.48414331e-02  1.28063534e-02  1.94968334e-01]
 [-9.02621967e-01 -2.19591891e-02 -4.74532031e-02  4.39543214e-03
   1.93338143e-03  2.24034645e-02 -2.59067396e-02  7.16176149e-02
   2.02542780e-01 -7.60581016e-02 -7.50194656e-02 -4.49026041e-01
  -5.27054151e-01 -3.43489119e+00 -1.58867141e-02 -6.01419031e-02
  -1.01226284e-02 -4.49764478e-02  3.75614755e-02  4.08593345e-02]
 [ 8.11721926e-01  4.94456428e-02 -1.05711467e-03 -1.53728038e-01
   3.45022234e-02 -9.81530533e-02 -1.68420624e-02 -3.66846420e-02
  -7.02671748e-02  1.15005917e-02  3.20185412e-02  4.56290024e-01
   4.09499007e-01  3.34458215e+00 -7.66744301e-02  4.66851366e-02
  -2.02628803e-02  7.11513474e-02 -1.11450474e-01 -9.08365165e-02]
 [ 2.67

**2.Using KNN Classification**

In [93]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [94]:
df.shape

(2000, 21)

In [95]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [96]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [97]:
df['price_range'].value_counts()


1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [98]:
x=df.drop('price_range',axis=1)
y=df['price_range']

print(type(x))
print(type(y))

print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


**Split the data into training and testing data**

In [99]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


**Building** **the model**

In [100]:
from sklearn.neighbors import KNeighborsClassifier

**Training the ML Model**

In [101]:
knn = KNeighborsClassifier(n_neighbors=12)
knn.fit(x_train,y_train)


KNeighborsClassifier(n_neighbors=12)

**Evaluate the training and testing score**

In [102]:
print('Training Score',knn.score(x_train,y_train))
print('Testing Score',knn.score(x_test,y_test))

Training Score 0.952
Testing Score 0.922


**Generate the Prediction**

In [103]:
ypred_knn = knn.predict(x_test)
print(ypred_knn)

[0 1 3 0 1 3 0 3 1 2 2 0 1 0 1 1 2 0 2 0 2 2 3 2 0 2 0 2 0 1 1 0 2 3 2 2 2
 1 3 2 2 0 0 1 2 1 2 1 3 1 3 3 0 0 0 2 0 2 3 1 0 3 1 2 3 2 2 3 2 2 1 3 2 3
 1 2 2 0 0 3 2 0 1 2 1 0 3 0 0 3 0 1 3 1 2 3 3 3 3 1 0 0 1 3 2 2 0 2 3 1 2
 3 2 3 3 2 0 3 0 0 3 2 0 2 3 0 3 3 1 1 1 2 0 0 2 1 0 2 1 0 1 0 0 2 2 1 3 0
 1 1 3 0 2 2 1 1 2 0 2 3 0 2 1 0 2 1 0 0 0 3 0 0 2 1 1 3 2 0 3 2 1 2 2 3 1
 2 2 3 2 0 3 1 3 2 3 1 3 1 2 0 1 1 0 3 0 2 2 0 0 0 0 0 2 0 1 1 0 0 3 0 0 1
 1 0 2 3 0 0 2 1 1 1 2 2 2 0 3 1 3 3 3 2 0 3 0 2 1 1 2 2 3 3 1 0 2 0 1 0 3
 3 2 0 3 1 2 1 0 0 1 0 1 0 1 3 1 2 0 2 1 1 3 2 0 2 2 2 0 3 2 3 0 0 2 2 3 2
 1 0 1 2 1 1 2 3 2 0 0 3 0 3 1 2 1 0 1 1 2 0 2 2 1 3 3 1 3 3 3 2 1 0 3 0 3
 3 2 2 1 0 1 3 1 2 2 0 2 0 3 1 1 0 0 3 0 3 2 3 0 3 3 1 3 0 1 0 3 3 3 3 1 0
 2 1 3 3 3 3 2 2 1 2 2 3 0 2 1 3 0 0 2 2 1 0 2 2 1 1 3 0 2 3 2 0 1 2 1 3 2
 0 1 2 1 1 1 0 1 2 0 2 0 2 1 0 2 0 2 1 3 3 1 1 1 2 3 3 1 1 0 3 3 2 1 0 3 1
 2 1 0 0 1 0 2 1 0 2 0 1 2 0 3 2 3 1 1 0 3 1 2 3 0 1 1 3 2 2 0 2 3 2 0 2 0
 3 3 3 2 3 1 3 1 0 0 2 3 

**Evaluation of the model**

In [104]:
from sklearn.metrics import confusion_matrix,classification_report

In [105]:
cm = confusion_matrix(y_test,ypred_knn)
print(cm)
print(classification_report(y_test,ypred_knn))


[[122   2   0   0]
 [  7 111   6   0]
 [  0   7 117   3]
 [  0   0  14 111]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       124
           1       0.93      0.90      0.91       124
           2       0.85      0.92      0.89       127
           3       0.97      0.89      0.93       125

    accuracy                           0.92       500
   macro avg       0.92      0.92      0.92       500
weighted avg       0.92      0.92      0.92       500



**3.Using SVM Classifier With linear
 kernel**

In [106]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [107]:
df.shape

(2000, 21)

In [108]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [109]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [110]:
r1=df['price_range'].value_counts()
r1

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [111]:
x=df.drop('price_range',axis=1)
y=df['price_range']

print(type(x))
print(type(y))

print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


**Split the data into training and testing data**

In [112]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


**Create the function to compute the confusion matrix,classification report**

In [113]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [114]:
def eval_model(ytest,ypred):
  cm = confusion_matrix(ytest,ypred)
  print('confusion matrix\n',cm)
  print('Acc Score',accuracy_score(ytest,ypred))
  print(classification_report(ytest,ypred,zero_division=0))


def mscore(model):
  print('Training score',model.score(x_train,y_train))
  print('Testing score',model.score(x_test,y_test))


**Model Building**

In [115]:
from sklearn.svm import SVC

In [116]:
m1=SVC(kernel='linear',C=1)
m1.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [117]:
mscore(m1)

Training score 0.992
Testing score 0.978


In [118]:
ypred_m1 =  m1.predict(x_test)
eval_model(y_test,ypred_m1)

# 54() misclassification

confusion matrix
 [[129   3   0   0]
 [  2 144   2   0]
 [  0   2 104   0]
 [  0   0   2 112]]
Acc Score 0.978
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       132
           1       0.97      0.97      0.97       148
           2       0.96      0.98      0.97       106
           3       1.00      0.98      0.99       114

    accuracy                           0.98       500
   macro avg       0.98      0.98      0.98       500
weighted avg       0.98      0.98      0.98       500



3.2 **Using SVM Classifier With Rbf**
 **kernel**

In [119]:
m2 = SVC(kernel='rbf',C=10,gamma=10)
m2.fit(x_train,y_train)

SVC(C=10, gamma=10)

In [120]:
mscore(m2)

Training score 1.0
Testing score 0.212


**Generate The Prediction**

In [121]:
ypred_m2 = m2.predict(x_test)
eval_model(y_test,ypred_m2)

confusion matrix
 [[  0   0 132   0]
 [  0   0 148   0]
 [  0   0 106   0]
 [  0   0 114   0]]
Acc Score 0.212
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       132
           1       0.00      0.00      0.00       148
           2       0.21      1.00      0.35       106
           3       0.00      0.00      0.00       114

    accuracy                           0.21       500
   macro avg       0.05      0.25      0.09       500
weighted avg       0.04      0.21      0.07       500



Among All the Above Model SVM with Linear kernel has best Accuracy.